### PR TITLE
Add Catppuccin theme

### PR DESCRIPTION
**Pull request by Xenfo**
Theme URL: https://github.com/catppuccin/catppuccin

### CODE REVIEW

**Review by 3kh0 — APPROVED** [review]
Looks good!

**Comment by Xenfo** [comment]
The theme recently split into variants, I will add them tonight so don't merge the PR yet.

**Comment by 3kh0** [comment]
@Xenfo convert this pr to a draft so ryo-ma knows

**Review by 3kh0 — APPROVED** [review]
Just tested this out on a deployment, looks good!

**Comment by Xenfo** [comment]
Closing as there are many more themes now, this PR is outdated.

**Pull request closed without merging**
