### PR TITLE
Add OG Account Trophy

### PR DESCRIPTION
**Pull request by SmashedFrenzy16**
Add a trophy called `OG Account` for those people who joined in 2008 (when GitHub released publicly for the first time). This is a `SECRET` trophy, for your information.

### CODE REVIEW

**Review by 3kh0 — APPROVED** [review]
Cool idea!

**Review by MitkoVtori — CHANGES_REQUESTED** [review]
I Approve this, but it might be better, if the points are, the number of years or months you've been on github. Eventually weeks or days. 👍

**Comment by ryo-ma** [comment]
@SmashedFrenzy16 
I don't think this pull request is working.
You have not added any conditional logic to `user_info.ts`.

https://github.com/ryo-ma/github-profile-trophy/blob/master/src/user_info.ts

**Comment by SmashedFrenzy16** [comment]
@ryo-ma I have added the conditional logic to `user_info.ts`.

**Comment by ryo-ma** [comment]
LGTM!

**Pull request merged**
