### PR TITLE
docs: fixed the issue of blue underline between hyperlinks & added some examples

### PR DESCRIPTION
**Pull request by Octopus058**
1. The reason for the blue underline between hyperlinks is that thetag in HTML automatically generates a blue underline, and adjacent hyperlinks are automatically connected. The solution is to use markdown to insert images.
2. Rearranged small tags such as star and forks in logical order.
3. Added several example images.
4. Fixed some statement  and format errors.

### CODE REVIEW

**Comment by ryo-ma** [comment]
> The reason for the blue underline between hyperlinks is that thetag in HTML automatically generates a blue underline, and adjacent hyperlinks are automatically connected. The solution is to use markdown to insert images.

The centering has come off.

**Comment by Octopus058** [comment]
> > The reason for the blue underline between hyperlinks is that thetag in HTML automatically generates a blue underline, and adjacent hyperlinks are automatically connected. The solution is to use markdown to insert images.
> 
> The centering has come off.

hmmm I don't understand what you meant.

**Comment by ryo-ma** [comment]
スクリーンショット 2024-09-25 10 47 58
This is the difference if you take that action.

The images are aligned to the left, so I would like to center them.

**Comment by ryo-ma** [comment]
It was my mistake in checking.
I checked the file instead of diff and there was no problem.

**Comment by ryo-ma** [comment]
However, CI is failing.
Can you run the deno fmt?

https://github.com/ryo-ma/github-profile-trophy/actions/runs/11016403533/job/30591819089?pr=300

**Comment by Octopus058** [comment]
How?




They are pretty fine in my view. and you can see they are just in the block of <div align="center">, so it shouldn't happen, weird :(

**Comment by ryo-ma** [comment]
The above was a misunderstanding on my part.
However, Formatter's CI is failing.
https://github.com/ryo-ma/github-profile-trophy/actions/runs/11016403533/job/30591819089?pr=300

Please run the `deno fmt` command to fix it.

**Comment by Octopus058** [comment]
> The above was a misunderstanding on my part.
> However, Formatter's CI is failing.
> https://github.com/ryo-ma/github-profile-trophy/actions/runs/11016403533/job/30591819089?pr=300
> 
> Please run the `deno fmt` command to fix it.

I'm too busy to fix it now, but I'll make it as soon as possible xD

**Review by Octopus058 — COMMENTED** [review]
Good

**Review by ryo-ma — APPROVED** [review]

**Pull request merged**
