### PR TITLE
theme: "alduin"

### PR DESCRIPTION
**Pull request by fuwn**

### CODE REVIEW

**Comment by ryo-ma** [comment]
@fuwn What does alduin mean?

**Comment by fuwn** [comment]
> @fuwn What does alduin mean?

i don't know if it has any meaning, but in this case, it's the name of the theme.
it's not super popular, but it is one of my personal favourites.

**Comment by ryo-ma** [comment]
@fuwn Also can you write a description of the theme in the theme section README?
https://github.com/ryo-ma/github-profile-trophy#apply-theme

**Comment by fuwn** [comment]
@ryo-ma yea sure! where'd you get the image from though, i can't seem to find a way to get the github user content for the theme.

**Comment by ryo-ma** [comment]
OK. I will write it.

**Pull request merged**
