### PR TITLE
Add a new theme named Gotham

### PR DESCRIPTION
**Pull request by Nanak360**
## Adding a new theme
Theme Name: Gotham

### I have attached a screenshot of the theme in use

Screenshot 2023-04-28 104011

### CODE REVIEW

**Review by MitkoVtori — APPROVED** [review]
I would use this theme. I wonder why it still is not approved.

**Comment by AlexcastroDev** [comment]
> ## Adding a new theme
> Theme Name: Gotham
> 
> ### I have attached a screenshot of the theme in use
> Screenshot 2023-04-28 104011

Thank you for your collab, sorry for waiting for long time. 

I will try review it and ask Ryo to merge this one.

**Comment by ryo-ma** [comment]
@Nanak360 Can you rebase?

**Review by CodeMaster7000 — APPROVED** [review]

**Comment by AlexcastroDev** [comment]
@Nanak360 can you check linter ?

**Pull request closed without merging**
