### PR TITLE
Remove the unknown trophies (as don't look good)

### PR DESCRIPTION
**Pull request by bhavberi**
Removed the unknown ranked trophies from the permanent trophies, as they don't look good on a profile...

### CODE REVIEW

**Comment by bhavberi** [comment]
@AlexcastroDev Requesting your review and suggestions

**Comment by AlexcastroDev** [comment]
@ryo-ma introduces unknows, he knows better if makes sense.

In my oppinion for this PR, you are not removing, but filtering. if we need to remove ( i dont know if it is necessary ), we should remove permanently. 
Also, missing tests.

**Comment by bhavberi** [comment]
Yeah, the trophies with 0 points (given the rank of Unknown) would not show on user profiles by default. Here, the meaning of remove meant from user badges.
Couldn't get what you mean by permanently?

**Comment by bhavberi** [comment]
Also, what kind of tests are missing?

**Comment by rajshish333** [comment]
how can i contribute , iam new to git

**Comment by iamxerrycan** [comment]
i am not getting

**Pull request closed without merging**
