### PR TITLE
Adding the matrix theme

### PR DESCRIPTION
**Pull request by Tubaleviao**

### CODE REVIEW

**Comment by TarunavBA** [comment]
> Oh, plus if you guys could add the 'hacktoberfest' topic to the repo, it would be awesome <3
@Tubaleviao no need for that.

**Comment by TarunavBA** [comment]
even the vercel check is not passing so not needed.

**Comment by Tubaleviao** [comment]
Why is this vercel thing? Is it something I should fix @TarunavBA ?

**Comment by TarunavBA** [comment]
No @Tubaleviao if it is very necessary @ryo-ma can approve it using his
administrative powers.

~ 🤖

**Comment by ryo-ma** [comment]
LGTM

**Comment by Tubaleviao** [comment]
Niiiiiiiiiiiiiiiiice, thanks @ryo-ma! It's already being used in production +.+

**Pull request merged**
