### PR TITLE
Refactor: code cleanup and xss fix

### PR DESCRIPTION
**Pull request by brenoepics**

### CODE REVIEW

**Review by ryo-ma — COMMENTED** [review]
Please check the CI.
https://github.com/ryo-ma/github-profile-trophy/actions/runs/9198142199/job/26035876438?pr=270

**Comment by brenoepics** [comment]
Fixed

**Comment by ryo-ma** [comment]
Can you check?
https://github.com/ryo-ma/github-profile-trophy/actions/runs/9452852730/job/26361857261?pr=270

**Comment by brenoepics** [comment]
I see, your GitHub Actions are too old, using checkout v2 (current v4) and [denolib/setup-deno](https://github.com/denolib/setup-deno) seems to be moved to [denoland/setup-deno](https://github.com/denoland/setup-deno)

**Comment by ryo-ma** [comment]
LGTM

**Pull request merged**
