### PR TITLE
Add OneStar theme

### PR DESCRIPTION
**Pull request by jos3s**
Theme created inspired by my[ One Star theme for Windows Terminal](https://windowsterminalthemes.dev/?theme=OneStar)
image

### CODE REVIEW

**Comment by ryo-ma** [comment]
Great!

**Review by ryo-ma — APPROVED** [review]

**Comment by jos3s** [comment]
@ryo-ma Could you update the readme with the new theme?

**Comment by ryo-ma** [comment]
@jos3s  Done

**Review by CodeMaster7000 — COMMENTED** [review]
Nice

**Pull request merged**
