### PR TITLE
GruvBox theme and Default theme

### PR DESCRIPTION
**Pull request by spenserblack**
For #4 

I've added some basic theming selectable from the URL params. Right now the options are `default` and `gruvbox`, but hopefully this PR opens the door to more themes :smiley: 

| Default | GruvBox |
| :---: | :---: |
| Themes demo | Themes demo |

There might need to be some changes -- C-rank trophies blend into the background. Maybe a different background should be selected from the GruvBox palette (below)? Or maybe the theme should change the color of some trophies?
GruvBox palette

I also added a very basic EditorConfig. If you don't want it, I can rebase it away :slightly_smiling_face:

### CODE REVIEW

**Comment by spenserblack** [comment]
Also, you might want to add a `GITHUB_TOKEN` to your preview settings in Vercel, so previews work properly in PRs :slightly_smiling_face:

**Comment by ryo-ma** [comment]
Great works!
But, the background color and trophy don't match.
I think it's because the color of the trophy is not the theme of gruvbox.
I think that it is necessary to take time to consider such as not changing the background color

It is very nice to be able to specify the theme from option parameter, so I want to firmly decide the rules about adding a theme.


If you make another pull request for editorconfig, I will merge.

**Comment by spenserblack** [comment]
>But, the background color and trophy don't match

Do you mean the white circle inside the trophy? I wasn't sure if it should always be white or match the background.

>I think that it is necessary to take time to consider such as not changing the background color

So I should keep the background always `#ffffff` for now? If so, no problem :slightly_smiling_face: :+1:

**Comment by ryo-ma** [comment]
I made samples.
How do you think of the following samples?

# Sample1
The following images keep the color of trophies. Only I changed the text color and next rank bar color.

スクリーンショット 2020-09-04 22 58 40
スクリーンショット 2020-09-04 22 59 39

# Sample2

Also, apply theme color to trophies.
I personally like it, but It takes time to apply.

スクリーンショット 2020-09-04 23 09 46
スクリーンショット 2020-09-04 23 30 10
スクリーンショット 2020-09-04 23 09 33
スクリーンショット 2020-09-04 23 31 48
スクリーンショット 2020-09-04 23 36 11

**Comment by spenserblack** [comment]
Wow, both look great! :art:

It is difficult to choose which is better. The gradients of the trophies in **Sample1** look good. But, in my personal opinion, **Sample2** is better, because having a dark background is closer to the "spirit" of dark themes.

Shall I proceed with making a theme like **Sample2**?

**Comment by ryo-ma** [comment]
OK. I agree. Let us support sample2
Can you realize **sample2**?
For that purpose, I want you to be able to set the color and shadow of each trophy according to the theme.

After that, I will make fine color adjustments.

**Comment by ryo-ma** [comment]
I have updated the master branch. Therefore if you can make the pull request, you necessary rebase your project.

**Comment by spenserblack** [comment]
No problem! I changed this PR back to a draft. Once I think it is ready, I'll change from draft to normal PR.

**Comment by spenserblack** [comment]
OK, I think this PR is ready for review 🙂 
I've tried to match **Sample2** closely.

I think I've made too many commits 😆 it might be good to squash merge.

Please let me know what you think!

**Review by ryo-ma — APPROVED** [review]

**Comment by ryo-ma** [comment]
Excellent! For the time being, I also merged them.
I also will fine-tune the color a little.

If there is anything else, I'll be waiting for a contribution😁

**Pull request merged**
