### PR TITLE
Update CONTRIBUTING.md to add a contribution guideline

### PR DESCRIPTION
**Pull request by CodeMaster7000**
This is a follow-up to issue #236 and creates a common, friendly ground so people can come to terms with how to commit to this repository.

### CODE REVIEW

**Comment by ryo-ma** [comment]
LGTM

**Comment by ryo-ma** [comment]
Can you check the CI? Please fmt.
https://github.com/ryo-ma/github-profile-trophy/actions/runs/6422379016/job/17438742963?pr=238

**Comment by CodeMaster7000** [comment]
@ryo-ma Can this PR be merged now?

**Comment by CodeMaster7000** [comment]
@ryo-ma There appears to be a formatting issue. Could you please commit the code to the PR  as a maintainer and merge? Thanks

**Comment by ryo-ma** [comment]
yes, I know that.
you should run the deno fmt

**Comment by CodeMaster7000** [comment]
@ryo-ma I have and it gives some additions and deletions - I'm not sure what to do.

**Comment by ryo-ma** [comment]
Check the https://github.com/ryo-ma/github-profile-trophy/blob/master/CONTRIBUTING.md#what-to-do-before-contributing.

And can you rebase?

**Comment by CodeMaster7000** [comment]
For some reason I can't commit again to this PR, so would it be possible for you to do so as a maintainer?

**Comment by ryo-ma** [comment]
I probably can't because this branch is your forked repository. 

Did you do a rebase? If you don't understand that, please study Github thoroughly.

**Comment by CodeMaster7000** [comment]
@ryo-ma I'm really sorry but it would be time-taking for me and unnecessarily a need to keep this PR open. I enabled edits by maintainers so it would be a quicker fix for you.

**Comment by CodeMaster7000** [comment]
For next time I will have studied them thoroughly, just that it will slow it down for a simple addition like this one :)

**Comment by ryo-ma** [comment]
I'm not in a hurry so I'll wait.
I'm not going to commit it to your repository.

If you do not fix it, I will close this PR and commit directly to my master branch. This method is the least labor-intensive for me.

**Comment by CodeMaster7000** [comment]
Sure

**Comment by CodeMaster7000** [comment]
@ryo-ma I believe the conflicts have been resolved now. I will now address the fmt. I am new to this so please request changes if I made an error somewhere.

Thank you so much for your patience.

**Comment by ryo-ma** [comment]
LGTM

**Pull request merged**
