### PR TITLE
Add Dracula theme

### PR DESCRIPTION
**Pull request by spenserblack**
This PR adds the [Dracula theme](https://github.com/dracula/dracula-theme).

Trophies C and B are flat, but trophies A and S get shadows because they are more exciting 😄 

What do you think?

### CODE REVIEW

**Comment by ryo-ma** [comment]
I think a good idea. But flat and shadow are different themes, It may damage the sense of unity. I thought that should use optional parameters for applying shadow If supporting shadow.

ex: &shadow=true

**Comment by spenserblack** [comment]
Understood. I can split Dracula into flat and shadowed versions.

**Comment by ryo-ma** [comment]
Yes. I'm glad you work. if you finished making this theme all flat, let me see.

**Comment by spenserblack** [comment]
OK, Dracula is all flat, except for the "secret" trophy, which is never flat in any of the themes.
Dracula Trophy Theme

**Comment by ryo-ma** [comment]
Thanks! Good contribution! I will merge.
But I want to change the **secret trophy color**, **text color**, and **rank bar color**. I want to emphasize red a little more and try not to overlap with other themes.

**Pull request merged**
